import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

export const myFont = localFont({src: './font/manda.woff2', variable: '--font-manda'})
export const inter = Inter({subsets: ["latin"], variable: '--font-inter'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.variable} ${inter.variable}`}>{children}</body>
    </html>
  );
}
